name: runwithme_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  dio: ^5.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  http: ^1.2.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
